### ISSUE TITLE
Health is not OK

### ISSUE THREAD

**Issue by arshpreetsingh** [carmstrong/multinode-ceph-vagrant#21]
My Cluster Health is not . OK, is the any way I can troubleshoot it ?
I am geting the following: 

```
vagrant@ceph-admin:~/test-cluster$  ceph -w
  cluster:
    id:     de6ff090-3c18-47a8-9651-6bda85920653
    health: HEALTH_WARN
            no active mgr
 
  services:
    mon: 3 daemons, quorum ceph-server-1,ceph-server-2,ceph-server-3
    mgr: no daemons active
    mds: cephfs-1/1/1 up  {0=ceph-server-1=up:active}
    osd: 3 osds: 3 up, 3 in
 
  data:
    pools:   0 pools, 0 pgs
    objects: 0 objects, 0B
    usage:   0B used, 0B / 0B avail
    pgs:     
 

```
